import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  weight: ["400", "700"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

import ClientSessionProvider from "@/components/ClientSessionProvider";
import Navbar from "@/components/Navbar";
import BottomNav from "@/components/BottomNav";
import FloatingMenu from "@/components/FloatingMenu";

function StarsFalling() {
  const stars = Array.from({ length: 120 }).map((_, i) => {
    const left = Math.random() * 100;
    const duration = 2 + Math.random() * 3;
    const delay = Math.random() * 5;
    const size = 1 + Math.random() * 2;
    return (
      <div
        key={i}
        className="star"
        style={{
          left: `${left}vw`,
          animationDuration: `${duration}s`,
          animationDelay: `${delay}s`,
          width: `${size}px`,
          height: `${size}px`,
        }}
      />
    );
  });
  return <div className="stars-bg">{stars}</div>;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansKR.variable} font-sans bg-black text-white`}>
        
        <ClientSessionProvider>
          <nav className="hidden md:block bg-black">
            <Navbar />
          </nav>
          <main className="flex flex-col items-center justify-start h-screen overflow-hidden px-1 py-1">
            {children}
          </main>
          <BottomNav />
          <FloatingMenu />
        </ClientSessionProvider>
        <div className="stars-bg" style={{ position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh', zIndex: 9999, pointerEvents: 'none' }}>
          <StarsFalling />
        </div>
      </body>
    </html>
  );
}
